//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeAccounting
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incomes
    {
        public int IdIncomes { get; set; }
        public Nullable<decimal> ValueOfIncome { get; set; }
        public string NameIncome { get; set; }
        public string TypeIncome { get; set; }
        public Nullable<System.DateTime> DateIncome { get; set; }

    }
}
