//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeAccounting
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int IdPayment { get; set; }
        public Nullable<decimal> ValuePayment { get; set; }
        public Nullable<System.DateTime> DatePayment { get; set; }
        public string ShopName { get; set; }
        public string PlaceName { get; set; }
        public string TypeName { get; set; }
        public Nullable<System.DateTime> Tmstmp { get; set; }
    }
}
